[project]
name = "flex"
version = "0.1.0"
description = "ScenarioMIP marker scenario extensions to 2500"
authors = ["Benjamin Sanderson"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64"]

[tasks]
notebook = "jupyter lab"
test = "python -m pytest tests"
test-cov = "pytest --cov=src"
pipeline = "python scripts/run_pipeline.py"

[dependencies]
python = ">=3.10,<3.13"
pandas = ">=3.0.1,<4"
numpy = ">=1.24"
matplotlib = ">=3.7"
seaborn = ">=0.12"
jupytext = ">=1.14"
jupyter = ">=1.0"
jupyterlab = ">=4.0"
openscm-units = ">=0.5"
tqdm = ">=4.65"
pip = "*"
openpyxl = "*"
pytest = "*"
pooch = ">=1.7"
pyyaml = ">=6.0"
scipy = ">=1.10"
papermill = ">=2.4"

[pypi-dependencies]
pandas-indexing = "*"
pandas-openscm=">=0.5.0"
fair = ">=2.2"

[feature.dev.dependencies]
ruff = ">=0.1"
black = ">=23.0"

[environments]
dev = ["dev"]
